name: PushGitlab

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
      env: 
        token: ${{ secrets.GITLAB_ACCESS_TOKEN }}

    - name: Push To Gitlab
      run: |
        echo Starting to push repo to gitlab
        git config user.name "Bhavishya"
        git config user.email "bhavishya@rapidinnovation.dev"
        git remote set-url origin "https://oauth2:${token}@gitlab.rapidinnovation.tech/root/node-backend-application.git"
        git push origin dev
